from typing import Final


DEFAULT_QUARK_PORT: Final[int] = 10000
MESSAGE_LENGTH_NUMBER_BYTE_COUNT = 4
QUARK_VERSION = "1.1"
RECENT_SERVERS_FILE_NAME = "Recent Servers.json"
MAX_RECENT_SERVERS_TO_SAVE = 20
